
export type Language = 'en' | 'ar';

export interface User {
  id: string;
  name: string;
  handle: string; // @username
  password?: string; // Stored locally for functional demo purposes
  avatar: string;
  banner?: string; // Profile header image
  role: 'student' | 'tutor' | 'enthusiast' | 'professional' | 'institute';
  instituteType?: 'School' | 'University' | 'Training Center' | 'Ministry' | 'Kindergarten' | 'Company';
  bio: string;
  points: number;
  followers: string[]; // Array of User IDs
  following: string[]; // Array of User IDs
  subscribedBoxIds?: string[]; // Array of Box IDs the user is subscribed to
  favoriteBoxIds?: string[]; // Array of Box IDs the user has favorited
  savedLessonIds?: string[]; // Array of Lesson IDs the user has saved/bookmarked
  streak?: number;
  lastLoginDate?: string; // ISO Date string or toDateString()
  // Tutoring Fields
  isTutor?: boolean;
  tutorSubjects?: string[];
  tutorRate?: number; // points per hour
  tutorRating?: number;
  tutorReviewCount?: number;
  tutorAvailability?: { day: number; startTime: string; endTime: string }[]; // 0 = Sunday, 6 = Saturday
  tutorRegion?: string;
  tutorLanguages?: string[];
}

export interface TutorSession {
  id: string;
  tutorId: string;
  studentId: string;
  subject: string;
  date: string;
  time: string;
  duration: number; // in minutes
  status: 'scheduled' | 'completed' | 'cancelled';
  price: number;
  meetingUrl?: string;
}

export interface Group {
  id: string;
  creatorId: string;
  name: string;
  description?: string;
  image?: string; // Unique image for the group
  memberIds: string[]; // List of User IDs in this group
  createdAt: string;
}

export interface Comment {
  id: string;
  userId: string;
  userName: string;
  userAvatar: string;
  content: string;
  timestamp: string;
}

export interface ForumPost {
  id: string;
  userId: string;
  userName: string;
  userAvatar: string;
  content: string;
  timestamp: string;
  replies: ForumPost[];
}

export interface Forum {
  id: string;
  title: string;
  description: string;
  posts: ForumPost[];
  createdAt: string;
}

export interface PollOption {
  id: string;
  text: string;
  votes: number;
  voterIds: string[];
}

export interface Poll {
  id: string;
  question: string;
  options: PollOption[];
  createdAt: string;
  creatorId: string;
}

export type QuizType = 
  | 'mcq_single' 
  | 'mcq_multi' 
  | 'true_false' 
  | 'short_answer' 
  | 'fill_blanks' 
  | 'sorting' 
  | 'drag_drop' 
  | 'matching' 
  | 'coloring';

export interface QuizContent {
  question: string;
  options?: string[]; // Used for MCQ, Sorting, DragDrop items
  correctAnswer?: any; // Can be index, array of indices, string, object, etc.
  pairs?: { left: string; right: string }[]; // For matching
  blanks?: string[]; // For fill in blanks
  coloringGrid?: number[]; // Simple grid definition for coloring
}

export interface AssessmentQuestion {
  id: string;
  type: QuizType;
  question: string;
  options?: string[];
  correctAnswer: any;
  feedback?: string; // Detailed feedback/explanation
}

export interface AssessmentContent {
  questions: AssessmentQuestion[];
  passingScore: number; // e.g., 70
}

export interface Lesson {
  id: string;
  boxId: string;
  title: string;
  content: string; // Markdown or text description
  type: 'text' | 'video' | 'quiz' | 'image' | 'audio' | 'html5' | 'scorm' | 'interactive_video' | 'pdf' | 'ppt' | 'assessment';
  quizType?: QuizType; // Specific type if lesson type is quiz
  quizData?: QuizContent; // Complex data for the quiz
  assessmentData?: AssessmentContent; // Full assessment data
  likes: number;
  comments: Comment[];
  isCompleted?: boolean;
  completionCount?: number; // Number of users who completed this lesson
  completedByUserIds?: string[]; // IDs of users who completed this
  timestamp: string;
  videoUrl?: string;
  imageUrl?: string;
  audioUrl?: string;
  html5Url?: string;
  html5Content?: string; // Raw HTML content generated by AI
  scormUrl?: string;
  interactiveVideoUrl?: string;
  pdfUrl?: string;
  pptUrl?: string;
  // Legacy support optional
  quizOptions?: string[]; 
  quizAnswer?: number; 
}

export interface Box {
  id: string;
  title: string;
  description: string;
  creatorId: string;
  creatorName: string;
  creatorAvatar: string;
  category: string;
  tags: string[]; // Hashtags associated with the box
  subscribers: number;
  lessons: Lesson[];
  forums?: Forum[]; // Optional discussion forums
  polls?: Poll[]; // Optional discussion polls
  isPrivate: boolean; // Retained for backward compatibility (true for premium/invite/private)
  accessLevel?: 'public' | 'premium' | 'invite_only' | 'private'; // New granular control
  price?: number; // Price in points. 0 or undefined = Free.
  coverImage: string;
  hasCertificate?: boolean; // If true, users get a certificate on completion
  // New Demographics & Filters - relaxed to string to allow custom values
  ageGroup?: string;
  difficulty?: string;
  region?: string; 
  language?: string; 
  genderAudience?: string;
  sharedWithUserIds?: string[]; // List of User IDs this box is explicitly shared with
  sharedWithGroupIds?: string[]; // List of Group IDs this box is explicitly shared with
}

export interface Transaction {
  id: string;
  type: 'credit' | 'debit';
  amount: number;
  description: string;
  timestamp: string;
  relatedBoxId?: string;
}

export interface Notification {
  id: string;
  type: 'like' | 'comment' | 'follow' | 'system' | 'event_join';
  actorId?: string; 
  actorName?: string;
  actorAvatar?: string;
  content: string;
  timestamp: string;
  isRead: boolean;
  targetId?: string; // Link to box or lesson
}

export interface Message {
  id: string;
  senderId: string;
  text: string;
  timestamp: string;
  // New Features
  replyTo?: { id: string; text: string; senderName: string };
  reactions?: Record<string, number>; // e.g. { '👍': 1, '❤️': 2 }
  attachment?: { type: 'image' | 'file'; url: string; name: string };
  status?: 'sent' | 'delivered' | 'read';
}

export interface Conversation {
  id: string;
  participantId: string; // If 1-on-1, this is the other user's ID
  groupId?: string; // If group chat, this is the group ID
  lastMessage: string;
  timestamp: string;
  unreadCount: number;
  messages: Message[];
}

export interface Event {
  id: string;
  title: string;
  date: string;
  time: string;
  attendees: number;
  image: string;
  type: 'Webinar' | 'Meetup' | 'Conference' | 'Workshop';
  isJoined?: boolean;
  description?: string;
  // New Privacy fields
  isPrivate?: boolean;
  creatorId?: string;
  invitedUserIds?: string[];
  sharedWithGroupIds?: string[]; // List of Group IDs this event is shared with
  // Location fields
  isOnline?: boolean;
  location?: string;
  meetingUrl?: string;
}

export interface Reminder {
  id: string;
  title: string;
  date: string; // Format: "Oct 25, 2024" to match mock events or ISO
  time: string;
  type: 'study' | 'deadline' | 'personal';
  isCompleted: boolean;
}

export enum ViewState {
  // Auth Views
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  
  // App Views
  DASHBOARD = 'DASHBOARD',
  EXPLORE = 'EXPLORE',
  MY_BOXES = 'MY_BOXES',
  NETWORK = 'NETWORK',
  CALENDAR = 'CALENDAR', // New View State
  BOX_DETAIL = 'BOX_DETAIL',
  LEADERBOARD = 'LEADERBOARD',
  CREATE = 'CREATE',
  PROFILE = 'PROFILE',
  USER_PROFILE = 'USER_PROFILE', 
  WALLET = 'WALLET',
  MESSAGING = 'MESSAGING',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ANALYTICS = 'ANALYTICS'
}
